apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: frontend
        image: alia153/final-project:frontend.4
        ports:
        - containerPort: 5001
        env:  
        - name: BACKEND_URL
          value: "http://backend-service.default.svc.cluster.local:5000"  
