---
- name: Deploy Jenkins 
  hosts: localhost
  become: yes

  tasks:
    - name: Pull Jenkins Docker image (lts-jdk17)
      docker_image:
        name: jenkins/jenkins
        tag: lts-jdk17
        source: pull

    - name: Create Jenkins container 
    
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk17
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        volumes:
          - "/var/jenkins_home:/var/jenkins_home"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "{{ ansible_env.HOME }}/.kube:/root/.kube" 
          - "/usr/local/bin/kubectl:/usr/local/bin/kubectl"  
